services:
  - type: web
    name: timetracker
    env: python
    plan: free
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn --worker-class sync -w 1 -b 0.0.0.0:$PORT main:app --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: TZ
        value: Europe/Madrid
      - key: FLASK_ENV
        value: production
      - key: APP_TIMEZONE
        value: Europe/Madrid

  - type: cron
    name: timetracker-auto-close
    env: python
    region: frankfurt
    schedule: "59 23 * * *"
    buildCommand: "./build.sh"
    startCommand: "python tasks/run_auto_close.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: TZ
        value: Europe/Madrid
      - key: FLASK_ENV
        value: production
      - key: APP_TIMEZONE
        value: Europe/Madrid
