services:
  - type: web
    name: timetracker
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:$PORT wsgi:app --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: FLASK_ENV
        value: production