"""Inicial: tablas base

Revision ID: e52bebf63ff7
Revises: 
Create Date: 2025-06-30 22:23:23.535943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e52bebf63ff7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_status', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('', 'Trabajado', 'Baja', 'Ausente', 'Vacaciones', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.create_unique_constraint('uix_employee_date', ['user_id', 'date'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.ENUM('', 'Cocina', 'Delivery', 'Reparto', 'Sala', collation='utf8mb4_unicode_ci'), server_default=sa.text("''"), nullable=True))
        batch_op.drop_constraint('uix_employee_date', type_='unique')
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('', 'Trabajado', 'Baja', 'Ausente', 'Vacaciones', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("''"))

    # ### end Alembic commands ###
