"""add_centro_to_user

Revision ID: fb26413c5b73
Revises: e52bebf63ff7
Create Date: 2025-07-08 22:47:12.962507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb26413c5b73'
down_revision = 'e52bebf63ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('centro', sa.Enum('-- Sin categoría --', 'Avenida de Brasil', 'Hortaleza', 'Las Tablas', 'Majadahonda', name='centro_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('centro')

    # ### end Alembic commands ###
